name: Release Helper

on:
  push:
    branches:
      - main

jobs:
  correct_repository:
    runs-on: ubuntu-latest
    steps:
      - name: fail on fork
        if: github.repository_owner == 'cmu-delphi'
        run: exit 1

  client_changed:
    needs: correct_repository
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Get Python client file changes
        id: changed-py
        uses: dorny/paths-filter@v3
        with:
          # when base and ref are the same, changes are detected against the most recent commit before the push.
          # see https://github.com/dorny/paths-filter#usage for details.
          base: 'main'
          ref: 'main'
          filters: |
            python_client_changed:
              - src/client/delphi_epidata.py
              - src/client/packaging/pypi/**
    outputs:
      python_client_changed: ${{ steps.changed-py.outputs.python_client_changed }}

  create_release:
    needs: correct_repository
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

  release_python_client:
    needs: [client_changed, create_release]
    if: needs.client_changed.outputs.python_client_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

  release_js_client:
    needs: create_release
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/client/packaging/npm
    steps:
      - name: Check out code
        uses: actions/checkout@v2

  sync_dev:
    needs: correct_repository
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: dev
          ssh-key: ${{ secrets.CMU_DELPHI_DEPLOY_MACHINE_SSH }}
      - name: Reset dev branch
        run: |
          git fetch origin main:main
          git reset --hard main
      - name: Create pull request into dev
        uses: peter-evans/create-pull-request@v3
        with:
          branch: bot/sync-main-dev
          commit-message: "chore: sync main-dev"
          base: dev
          title: "chore: sync main->dev"
          body: |
            Syncing Main->Dev.
